### ISSUE TITLE
Better way to specify request parameters

### ISSUE THREAD

**Issue by ktonon** [ktonon/aws-sdk-elm#16]
For example,

```elm 
getObject : String -> String -> Date -> String -> Date -> String -> String -> String -> String -> String -> String -> String -> Date -> String -> String -> String -> String -> RequestPayer -> Int -> AWS.ServiceConfig -> AWS.Http.UnsignedRequest GetObjectOutput
getObject bucket ifMatch ifModifiedSince ifNoneMatch ifUnmodifiedSince key range responseCacheControl responseContentDisposition responseContentEncoding responseContentLanguage responseContentType responseExpires versionId sSECustomerAlgorithm sSECustomerKey sSECustomerKeyMD5 requestPayer partNumber serviceConfig =
```

but only bucket and key are required. key does not even appear as the second parameter. Need to think of a better way to handle this

**Comment by ktonon** [comment]
One possible solution:

```elm
getObject : String -> String -> GetObjectOptions -> AWS.ServiceConfig -> AWS.Http.UnsignedRequest GetObjectOutput
getObject bucket key options serviceConfig =
```

where `GetObjectOptions` contains maybes for everything else. To construct it in a more readable way than setting a bunch of `Nothing` values, we could have an empty options constructor:

```
getObjectOptions : GetObjectOptions
```

which gives the record with all values set to `Nothing`. Then the record update syntax can be used to set the desire values

**Comment by nickmonad** [comment]
I like that approach. It makes the required parameters more explicit than wrapping those up with the optional parameters into a single record, and essentially provides implicit validation that the caller is providing everything required - especially since elm doesn't have reflection (iirc)

**Comment by ktonon** [comment]
I'm also thinking of taking out the `AWS.ServiceConfig` value from the function which creates the unsigned request. It can be provided along with the date when the request gets signed. I'm not happy about the two step process to create and then sign a request, but I did it that way because getting the current date requires an 
effect

**Comment by ktonon** [comment]
I'm going to put signing on hold and do this first.

**Comment by ktonon** [comment]
#17
