### ISSUE TITLE
Service endpoints are not correct

### ISSUE THREAD

**Issue by ktonon** [ktonon/aws-sdk-elm#23]
Example `SQS.elm` we attempt to use `sqs.amazonaws.com`, but it should be `queue.amazonaws.com`

**Comment by bjufre** [comment]
@ktonon Hi! Reading on 'AWS Regions and Endpoints' in the documentation says that `queue.amazonaws.com` for example is the legacy endpoint for the AWS CLI or the SDK for Python. Do you find this to be the issue in any other case?

**Comment by ktonon** [comment]
@behind-design thanks for the feedback. Got tunnel vision parsing the JSON description of the apis, and should have just read the docs. I've confirmed that adding the region fixes the issue, and so `sqs` is actually part of the correct endpoint. So for `us-east-1`, it would be `sqs.us-east-1.amazonaws.com`.

**Comment by ktonon** [comment]
I'm trying to keep the rules for generating the endpoint derived from the json description of the api. So looking at those [AWS Regions and Endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html) I see that most services (such as sqs) require a region as part of the endpoint, but for other services (like ec2) the region is optional. The final case are services like `iam` which do not support regions. Looking at json examples from each:

__sqs__

```json
  "metadata":{
    "apiVersion":"2012-11-05",
    "endpointPrefix":"sqs",
    "protocol":"query",
    "serviceAbbreviation":"Amazon SQS",
    "serviceFullName":"Amazon Simple Queue Service",
    "signatureVersion":"v4",
    "uid":"sqs-2012-11-05",
    "xmlNamespace":"http://queue.amazonaws.com/doc/2012-11-05/"
  },
```

__ec2__

```json
  "metadata":{
    "apiVersion":"2016-11-15",
    "endpointPrefix":"ec2",
    "protocol":"ec2",
    "serviceAbbreviation":"Amazon EC2",
    "serviceFullName":"Amazon Elastic Compute Cloud",
    "signatureVersion":"v4",
    "uid":"ec2-2016-11-15",
    "xmlNamespace":"http://ec2.amazonaws.com/doc/2016-11-15"
  },
```

__iam__

```json
  "metadata":{
    "apiVersion":"2010-05-08",
    "endpointPrefix":"iam",
    "globalEndpoint":"iam.amazonaws.com",
    "protocol":"query",
    "serviceAbbreviation":"IAM",
    "serviceFullName":"AWS Identity and Access Management",
    "signatureVersion":"v4",
    "uid":"iam-2010-05-08",
    "xmlNamespace":"https://iam.amazonaws.com/doc/2010-05-08/"
  },
```

I think we can say if a service `metadata` has a `globalEndpoint`, then we should use it, otherwise we use the `endpointPrefix` and region. S3 also has the `globalEndpoint`.

**Comment by ktonon** [comment]
Since I can't see any difference between `sqs` and `ec2`, then we'll just always provide the region even if it is optional.

**Comment by ktonon** [comment]
@behind-design I've opened a PR to resolve this issue. Thanks for the help!

**Comment by bjufre** [comment]
@ktonon No problem! Really glad to be of help! 

Thanks for this amazing work it's incredible!

**Comment by bjufre** [comment]
@ktonon Should this issue be closed then? 😀

**Comment by ktonon** [comment]
Yeah, will be when @ngmiller approves the #26 . We work off-workday hours on this project. I'm in the north american eastern timezone. Nick is two hours behind me. @behind-design are you interested in collaborating? If so I can add you to the project and you can also review PRs.

**Comment by bjufre** [comment]
I'd love to! I've been taking a look on off-work hours to! hahaha

**Comment by bjufre** [comment]
@ktonon Right know I'm reviewing about the recursive types like `AttributeValue` which is a little tricky... :|

**Comment by ktonon** [comment]
Agreed, that is tricky one. You can assign yourself to the issue, so that we know you are working on it

**Comment by nickmonad** [comment]
Thanks @behind-design! #26 has been merged
