### ISSUE TITLE
Handle pre-signing for S3 (and others)

### ISSUE THREAD

**Issue by nickmonad** [ktonon/aws-sdk-elm#24]
from slack convo:

> Actually, maybe S3 is not a good example to test auth. I think there might be some differences in auth, I remember seeing some pre-signing stuff in the js v4 signer, which we do not implement. Maybe try searching for some other GET request that takes no arguments in another service. Or, we should just fix the query params/request body first

**Comment by nickmonad** [comment]
@ktonon Just glancing through the s3 docs and found this: http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html, more specifically:

> This topic explains authenticating requests using Signature Version 2. Amazon S3 now supports the latest Signature Version 4. This latest signature version is supported in all regions and any new regions after January 30, 2014 will support only Signature Version 4.

So maybe we don't need the `S3Signature` after all?

**Comment by ktonon** [comment]
nice find!
